In [2]:
"""
6 

python logging
CRITICAL,ERROR,WARNING,INFO,BEBUG

datetime module -> datetime.now()で現在時刻のインスタンスを得る

pathlib module -> Path.glob()にワイルドカードでファイルを取得できたりする



7 

%whos（型も見れる） %who で変数を確認出来る

Notebook形式の拡張子は ipynb

Notebook形式 (.ipynb) はJSONファイル

%,%% -> マジックコマンド 実行時間を確認出来たりする
%timeit(その行のみ)
%%timeit(セル）


"""

'\n6 \n\npython logging\nCRITICAL,ERROR,WARNING,INFO,BEBUG\n\ndatetime module -> datetime.now()で現在時刻のインスタンスを得る\n\npathlib module -> Path.glob()にワイルドカードでファイルを取得できたりする\n\n\n\n7 \nNotebook形式 (.ipynb) はJSONファイル\n\n\n'

In [24]:
"""
15 numpyのスライスの復習

"""

import numpy as np
a = np.arange(10)
b = np.arange(5*5).reshape(5,5)

print("\nslice plac")
print(a[0:7:3])  # 0<= i < 7 で、2個とばし
print(a[:-3:2])  # -3 (len(a)-3 index:7 の手前まで、1個とばし)

print(b[-3:,[0,3,4]])  # b[行指定,列指定]

    # "-3:" -> indexで行数-3のところから最後まで
    # 0-indexed で、[0,3,4]列目
    # 組み合わせる

print(b[[0,2,4],[0,2,4]])  # お絵描きロジック的な指定方法

"""
16
"""
e = np.eye(3)
print("\n E 3by3")
print(e)


rng3 = np.arange(0,10,3)
rng4 = np.arange(0,10,4)

print("\narange : 0 <= i < 10")
print(rng3)
print(rng4)


slice plac
[0 3 6]
[0 2 4 6]
[[10 13 14]
 [15 18 19]
 [20 23 24]]
[ 0 12 24]

 E 3by3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange : 0 <= i < 10
[0 3 6 9]
[0 4 8]


In [32]:
"""
23 
nm.random.randint(A,B,C)
A <= x < B の乱数を C 個

"""

'\n23 \nnm.random.randint(A,B,C)\n\n'

In [31]:
"""
20 pandas 復習

index , column 引数 or 属性で指定(リストを渡す)

行のスライス指定と列のリストによる指定(SQL的)
df[(スライス)][["col","col"]]

df.loc["index名","カラム名"]

df.iloc[2,2] -> 3行目3列目

df.iloc[0:10,0:3] 1~10行目 , 1~3行目


22
データフレームの列の指定と併せて条件を指定することで、条件にあった行からなるデータフレームを抽出する

query = df["col"] > value
    条件にあうインデックスを真理値で持っている変数

df[query]
    条件に合ったデータのみになっている

※条件式のブール演算では、`and`, `or`, `not` の代わりに `&`, `|`, `~` を用いる。

"""

'\n20 pandas 復習\n\n'